# Generated by Django 5.2.5 on 2026-08-11 14:57

import django.core.validators
import django.db.models.deletion
import learning.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=160)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('summary', models.TextField()),
                ('audience', models.CharField(blank=True, max_length=240)),
                ('total_days', models.PositiveSmallIntegerField(default=0)),
                ('estimated_weeks', models.PositiveSmallIntegerField(default=0)),
                ('accent_start', models.CharField(default='#3b7d6b', max_length=16)),
                ('accent_end', models.CharField(default='#ef8354', max_length=16)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', '进行中'), ('paused', '已暂停'), ('completed', '已完成')], default='active', max_length=12)),
                ('current_day', models.PositiveSmallIntegerField(default=1)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_studied_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='learning.learningplan')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DayProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', '未开始'), ('in_progress', '进行中'), ('completed', '已完成')], default='not_started', max_length=16)),
                ('acceptance_checks', models.JSONField(blank=True, default=list)),
                ('reflection', models.TextField(blank=True)),
                ('recall_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='learning.enrollment')),
            ],
            options={
                'ordering': ['plan_day__day_number'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('commit', 'Git提交'), ('code', '代码'), ('test', '测试结果'), ('log', '日志'), ('report', '报告'), ('link', '链接'), ('note', '学习笔记')], max_length=12)),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('attachment', models.FileField(blank=True, upload_to=learning.models.evidence_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='learning.dayprogress')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Gap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('detail', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', '待解决'), ('resolved', '已解决')], default='open', max_length=12)),
                ('resolution', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gaps', to='learning.dayprogress')),
            ],
            options={
                'ordering': ['status', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveSmallIntegerField()),
                ('phase', models.CharField(max_length=160)),
                ('week_number', models.PositiveSmallIntegerField()),
                ('week_title', models.CharField(max_length=160)),
                ('title', models.CharField(max_length=200)),
                ('core_knowledge', models.TextField()),
                ('hands_on_task', models.TextField()),
                ('acceptance_criteria', models.JSONField(default=list)),
                ('estimated_minutes', models.PositiveSmallIntegerField(default=120)),
                ('content', models.JSONField(blank=True, default=list)),
                ('reference_answer', models.TextField(blank=True)),
                ('commands', models.JSONField(blank=True, default=list)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='learning.learningplan')),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
        migrations.AddField(
            model_name='dayprogress',
            name='plan_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='learning.planday'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('user', 'plan'), name='unique_user_plan'),
        ),
        migrations.AddConstraint(
            model_name='planday',
            constraint=models.UniqueConstraint(fields=('plan', 'day_number'), name='unique_plan_day'),
        ),
        migrations.AddConstraint(
            model_name='dayprogress',
            constraint=models.UniqueConstraint(fields=('enrollment', 'plan_day'), name='unique_day_progress'),
        ),
    ]
