# Generated by Django 5.2.5 on 2026-08-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayprogress',
            name='knowledge_checks',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
