# Generated by Django 5.2.5 on 2026-08-12 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_planfeedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='learningplan',
            name='fork_note',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='learningplan',
            name='forked_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forks', to='learning.learningplan'),
        ),
        migrations.AddField(
            model_name='planday',
            name='community_supplements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='BuddyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_time', models.CharField(max_length=80)),
                ('goal', models.CharField(max_length=240)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buddy_profile', to='learning.enrollment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buddy_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('course', '课程共建'), ('review', '同伴互评'), ('answer', '志愿答疑')], max_length=12)),
                ('title', models.CharField(max_length=160)),
                ('detail', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HelpSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('open', '征集中'), ('archived', '已归档')], default='open', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_help_sessions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='help_sessions', to='learning.learningplan')),
            ],
            options={
                'ordering': ['status', 'deadline'],
            },
        ),
        migrations.CreateModel(
            name='HelpQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteer_answers', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_questions', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning.helpsession')),
            ],
            options={
                'ordering': ['answered_at', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PeerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', '等待互评'), ('claimed', '评审中'), ('completed', '已完成')], default='open', max_length=12)),
                ('accuracy', models.BooleanField(blank=True, null=True)),
                ('runnable', models.BooleanField(blank=True, null=True)),
                ('clarity', models.BooleanField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_reviews', to='learning.dayprogress')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_peer_reviews', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_peer_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已采纳'), ('rejected', '未采纳')], default='pending', max_length=12)),
                ('review_note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_suggestions', to=settings.AUTH_USER_MODEL)),
                ('plan_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_suggestions', to='learning.planday')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_suggestions', to='learning.communitypost')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('post', 'plan_day'), name='unique_post_course_suggestion')],
            },
        ),
    ]
