# Generated by Django 5.2.5 on 2026-08-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_learningplan_fork_note_learningplan_forked_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('active', '进行中'), ('paused', '已暂停'), ('completed', '已完成'), ('withdrawn', '已退出')], default='active', max_length=12),
        ),
    ]
