# Generated by Django 5.2.5 on 2026-08-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_alter_enrollment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='planday',
            name='content_edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
