# Generated by Django 5.2.5 on 2026-08-23 10:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_remove_learningplan_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('forgot', '需要重学'), ('unsure', '基本想起'), ('mastered', '熟练掌握')], max_length=12)),
                ('note', models.TextField(blank=True)),
                ('interval_days', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('next_review_at', models.DateTimeField()),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_attempts', to='learning.dayprogress')),
            ],
            options={
                'ordering': ['-reviewed_at'],
            },
        ),
    ]
