# Generated by Django 5.2.5 on 2026-08-26 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0012_study_groups_contracts_notifications'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='kind',
            field=models.CharField(choices=[('course', '课程共建'), ('review', '同伴互评'), ('answer', '志愿答疑'), ('challenge', '小队挑战')], max_length=12),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('community', '社区互动'), ('review', '同伴互评'), ('help', '公开答疑'), ('course', '课程共建'), ('gap', '缺口验证'), ('challenge', '小队挑战'), ('system', '系统通知')], default='system', max_length=16),
        ),
        migrations.CreateModel(
            name='TeamChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('open', '进行中'), ('completed', '已完成')], default='open', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_team_challenges', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='learning.studygroup')),
            ],
            options={
                'ordering': ['status', 'deadline', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamChallengeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('reproduce', '复现'), ('test', '测试'), ('explain', '讲解'), ('review', '复核')], max_length=12)),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='learning.teamchallenge')),
                ('evidence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_challenge_entries', to='learning.evidence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_challenge_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('challenge', 'user'), name='unique_team_challenge_member'), models.UniqueConstraint(fields=('challenge', 'role'), name='unique_team_challenge_role')],
            },
        ),
    ]
