# Generated by Django 5.2.5 on 2026-08-27 10:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0013_alter_contribution_kind_alter_notification_kind_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic')], max_length=24)),
                ('model', models.CharField(max_length=100)),
                ('context_rounds', models.PositiveSmallIntegerField(default=8, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(12)])),
                ('max_output_tokens', models.PositiveSmallIntegerField(default=1024, validators=[django.core.validators.MinValueValidator(128), django.core.validators.MaxValueValidator(4096)])),
                ('teaching_mode', models.CharField(choices=[('hint', '提示优先'), ('explain', '详细讲解'), ('example', '举例对比'), ('debug', '报错分析'), ('quiz', '出题检验')], default='hint', max_length=16)),
                ('include_current_lesson', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('progress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_chat_sessions', to='learning.dayprogress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', '用户'), ('assistant', '助手')], max_length=12)),
                ('content', models.TextField()),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('context_snapshot', models.JSONField(blank=True, default=dict)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('provider_request_id', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='learning.aichatsession')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AIProviderCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic')], max_length=24)),
                ('encrypted_api_key', models.TextField()),
                ('key_last_four', models.CharField(max_length=4)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['provider'],
            },
        ),
        migrations.AddIndex(
            model_name='aichatsession',
            index=models.Index(fields=['user', '-updated_at'], name='ai_chat_user_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='aichatmessage',
            index=models.Index(fields=['session', 'created_at'], name='ai_msg_session_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='aiprovidercredential',
            constraint=models.UniqueConstraint(fields=('user', 'provider'), name='unique_user_ai_provider'),
        ),
    ]
