# Generated by Django 5.2.5 on 2026-08-27

from django.db import migrations, models


class Migration(migrations.Migration):
    """为 AI 密钥和会话增加用户选择的接口协议与 HTTPS 地址。"""

    dependencies = [
        ("learning", "0014_aichatsession_aichatmessage_aiprovidercredential_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiprovidercredential",
            name="adapter",
            field=models.CharField(
                blank=True,
                choices=[
                    ("openai_responses", "OpenAI Responses"),
                    ("openai_chat_completions", "OpenAI Chat Completions"),
                    ("anthropic_messages", "Anthropic Messages"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="aiprovidercredential",
            name="api_url",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="aiprovidercredential",
            name="model",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="aichatsession",
            name="adapter",
            field=models.CharField(
                blank=True,
                choices=[
                    ("openai_responses", "OpenAI Responses"),
                    ("openai_chat_completions", "OpenAI Chat Completions"),
                    ("anthropic_messages", "Anthropic Messages"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="aichatsession",
            name="api_url",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
